# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=1000)),
                ('source', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
