# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Default Title Post', max_length=500),
        ),
    ]
